name: gps_plugin
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'


flutter:
  plugin:
    platforms:
      android:
        default_package: my_plugin_android
      ios:
        default_package: my_plugin_ios

dependencies:
  flutter:
    sdk: flutter
  my_plugin_android:
    path: ../my_plugin_android
  my_plugin_ios:
    path: ../my_plugin_ios
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




